add_library(
    columnar_exec_expression
    STATIC
    comparison.cpp
    column_ref.cpp
    arithmetic.cpp
    logical.cpp
    like.cpp
    date_trunc.cpp
    not.cpp
    string_len.cpp
    case_when.cpp
    regex_replace.cpp
)

target_include_directories(
    columnar_exec_expression
    PUBLIC
    ${CMAKE_SOURCE_DIR}/src
)

target_link_libraries(
    columnar_exec_expression
    PUBLIC
    columnar_core
    columnar_exec_core
    columnar_exec_interface
    re2::re2
    absl::flat_hash_set
    absl::inlined_vector
)
